avatar:
  enable: true
  url: /images/2.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false


colors:
  primary: '#134857'
  bg: '#baccd9'
  selection_bg: '#132c33'

tags:
  Vue: '#4fc08d'
  Hexo: '#0E834D'
  CSS: '#5298d1'
  Node.js: '#026E00'
  Git: '#F14E32'
  React: '#61dafb'
  Python: '#3776ab'
  PHP: '#8892BF'
  VS Code: '#0066B8'
  JavaScript: '#F4DF4F'
  TypeScript: '#317AC6'
  Laravel: '#F4645F'

head:
  js:
    async:
      # 这里是你从 iconfont 处获得的图标链接。
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
  css:
    fonts: https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap


social:
  - name: 微博
    link: https://weibo.com/u/1961597597
    icon: ri:weibo-line
    color: '#E6162D'
  - name: 网易云音乐
    link: https://y.music.163.com/m/user?id=515509052
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'

banner:
  enable: true
  title: 伊九得玖的小站
  border: true
  cloud:
    enable: true
    color: 'ccccd6'
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# 可选 light | dark | auto | time
mode: auto


bg_image:
  enable: true
  url: span
  # bg_image: /images/3.jpg
  # dark:
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8

search:
  modal: true
  bg_image: /images/2.jpg
  dark_bg_image: false
  # placeholder:

fireworks:
  enable: true
  colors:
    - '22, 97, 171'
    - '97, 154, 195'
    - '186, 204, 217'

medium_zoom: true


scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

sidebar:
  bg_image:  
  bg_position: bottom 1rem center
  tagcloud:
    enable: false
    amount: 20

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
  custom:
    title: 文档
    path:
    icon: ri:settings-line

pages:

post_card:
  opacity: 0.8
  color: '#d8e3e7'

types:
  link:
    color: blue
    icon: ri:external-link-line
  bilibili:
    color: '#FF8EB3'
    icon: ri:bilibili-line
  douban:
    color: '#007722'
    icon: ri:douban-line
  github:
    color: black
    icon: ri:github-line
  netease-cloud-music:
    color: '#C10D0C'
    icon: ri:netease-cloud-music-line
  notion:
    color: black
    icon: ri:notion
  twitter:
    color: '#1da1f2'
    icon: ri:twitter-line
  wechat:
    color: '#1AAD19'
    icon: ri:wechat-2-line
  weibo:
    color: '#E6162D'
    icon: ri:weibo-line
  yuque:
    color: '#25b864'
    icon: ant-design:yuque-outlined
  zhihu:
    color: '#0084FF'
    icon: ri:zhihu-line

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: 很遗憾，咱没写啥目录
  collapse: false

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: false

footer:
  since: 2022
  icon:
    name: ri:cloud-line
    animated: true
    color: '#0078E7'
    since: 2022
    icon:
      name: ri:cloud-line
      animated: true
      color: '#0078E7'
      url: span
    powered:
      enable: true
      live_time:
    enable: ture
    prefix: 本博客已艰难地运行
    suffix: (●'◡'●)
    start_time: '2022-09-23T00:00:00'
      
say:
  enable: true
  api: /data/sentences.json
  hitokoto:
    enable: false

mourn:
  enable: true
  days:
    - 4-4

albums:
  enable: true

 
